import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SidebarDesktop } from "@/components/sidebarDesktop";
import { Bell, Home, User } from "lucide-react";
import { Sidebar } from "@/components/sidebar";
import Apresentacao from './apresentacao'
import { UserProvider } from "../context/UserProvider";
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {


    return (
            <div className="bgBranco md:flex">
                <aside className="flex-shrink-0  md:fixed">
                    <Apresentacao />
                </aside>    
                <main className="md:flex-grow mb-10 md:ms-[550px]">
                    {children}
                </main>
            </div>
    );

}
